import sys
import time
sys.path.append(r'Bare')
from mysqldb import MysqlDB
from redisdb import RedisDB
from memcachedb import MemcacheDB

DB = MysqlDB()
#data = DB.query("SHOW TABLES")
#print ( data )
#DB.selectDB('mysql')
#data = DB.query("SHOW TABLES")
#print ( data )
DB.selectDB('29shu_book')
res = DB.find('Book',{'BookId':['>', 5]},'*', '', [5,5])
print (res)

rds = RedisDB()
#res = rds.get('mykey1')
#print(res)
#rds.set('age', 28)
#res = rds.get('age')
#print(res)
#rds.set({'age':28,'sex':'男','time':time.time()})
#res = rds.get(['sex','age'])
#rds.rpush('list', 1,2,3)
#res = rds.lrange('list')
#res = rds.rpop('list')
#res = rds.lindex('list')
#rds.rpush('list', 'a','b','c')
#res = rds.llen('list')
#rds.delete('list')
#rds.move('list',1)
#rds.selectDB(1)
#res = rds.exists('list')
#print(res)
#rds.decr('age')
#res = rds.get('age')
#rds.hset('camfee',{'age':28,'sex':'男','time':time.time()})
#res = rds.hget('camfee', ['sex','age'])
#res = rds.hscan('camfee',1)
#rds.sadd('set1', {'aa':11, 'cc': 23, 'dd': 323})
#res = rds.smembers('set1')
#rds.srem('set1',{'aa':11, 'cc': 23, 'dd': 323})
#res = rds.scard('set1')
#res = rds.spop('set1')
#print(res)

mem = MemcacheDB()
#mem.set({'age':28,'sex':'男','time':time.time()})
#res = mem.get(['age','sex'])
#mem.set('age',28)
#res = mem.get('time')
#print(res)
